// <auto-generated />
using System;
using LexiLoop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LexiLoop.Data.Migrations
{
    [DbContext(typeof(LexiLoopDbContext))]
    [Migration("20260911162529_AddCollectionUpdatedAt")]
    partial class AddCollectionUpdatedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LexiLoop.Models.Entities.Collection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("LexiLoop.Models.Entities.LearningProgress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CorrectCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("ForeignToTranslationDifficulty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(5.0);

                    b.Property<int>("ForeignToTranslationIntervalDays")
                        .HasColumnType("integer");

                    b.Property<int>("ForeignToTranslationLapseCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ForeignToTranslationLastReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ForeignToTranslationLevel")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ForeignToTranslationNextReviewAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ForeignToTranslationReviewCount")
                        .HasColumnType("integer");

                    b.Property<double>("ForeignToTranslationStability")
                        .HasColumnType("double precision");

                    b.Property<int>("ForeignToTranslationState")
                        .HasColumnType("integer");

                    b.Property<int>("IncorrectCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<double>("TranslationToForeignDifficulty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(5.0);

                    b.Property<int>("TranslationToForeignIntervalDays")
                        .HasColumnType("integer");

                    b.Property<int>("TranslationToForeignLapseCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("TranslationToForeignLastReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TranslationToForeignLevel")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("TranslationToForeignNextReviewAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TranslationToForeignReviewCount")
                        .HasColumnType("integer");

                    b.Property<double>("TranslationToForeignStability")
                        .HasColumnType("double precision");

                    b.Property<int>("TranslationToForeignState")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("VocabularyItemId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ForeignToTranslationNextReviewAt");

                    b.HasIndex("TranslationToForeignNextReviewAt");

                    b.HasIndex("VocabularyItemId")
                        .IsUnique();

                    b.ToTable("LearningProgress");
                });

            modelBuilder.Entity("LexiLoop.Models.Entities.LearningSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AnswerRevealed")
                        .HasColumnType("boolean");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentIndex")
                        .HasColumnType("integer");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<int>("MessageId")
                        .HasColumnType("integer");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("LearningSessions");
                });

            modelBuilder.Entity("LexiLoop.Models.Entities.LearningSessionCard", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<long>("VocabularyItemId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("VocabularyItemId");

                    b.HasIndex("SessionId", "Position")
                        .IsUnique();

                    b.ToTable("LearningSessionCards");
                });

            modelBuilder.Entity("LexiLoop.Models.Entities.ReviewHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<int>("Result")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("VocabularyItemId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ReviewedAt");

                    b.HasIndex("VocabularyItemId");

                    b.ToTable("ReviewHistory");
                });

            modelBuilder.Entity("LexiLoop.Models.Entities.TelegramUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("InputMode")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("TelegramUserId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LexiLoop.Models.Entities.UserSettings", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("DefaultLearningMode")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("LastNotificationDate")
                        .HasColumnType("date");

                    b.Property<int>("NewItemsPerDay")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("ReviewNotificationTime")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("ReviewNotificationsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowPronunciation")
                        .HasColumnType("boolean");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("LexiLoop.Models.Entities.VocabularyItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ForeignText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsLearningEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Pronunciation")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "ForeignText", "Translation")
                        .IsUnique();

                    b.ToTable("VocabularyItems");
                });

            modelBuilder.Entity("LexiLoop.Models.Entities.VocabularyItemCollection", b =>
                {
                    b.Property<long>("VocabularyItemId")
                        .HasColumnType("bigint");

                    b.Property<long>("CollectionId")
                        .HasColumnType("bigint");

                    b.HasKey("VocabularyItemId", "CollectionId");

                    b.HasIndex("CollectionId");

                    b.ToTable("VocabularyItemCollections");
                });

            modelBuilder.Entity("LexiLoop.Models.Entities.Collection", b =>
                {
                    b.HasOne("LexiLoop.Models.Entities.TelegramUser", "User")
                        .WithMany("Collections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LexiLoop.Models.Entities.LearningProgress", b =>
                {
                    b.HasOne("LexiLoop.Models.Entities.VocabularyItem", "VocabularyItem")
                        .WithOne("Progress")
                        .HasForeignKey("LexiLoop.Models.Entities.LearningProgress", "VocabularyItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VocabularyItem");
                });

            modelBuilder.Entity("LexiLoop.Models.Entities.LearningSession", b =>
                {
                    b.HasOne("LexiLoop.Models.Entities.TelegramUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LexiLoop.Models.Entities.LearningSessionCard", b =>
                {
                    b.HasOne("LexiLoop.Models.Entities.LearningSession", "Session")
                        .WithMany("Cards")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LexiLoop.Models.Entities.VocabularyItem", "VocabularyItem")
                        .WithMany()
                        .HasForeignKey("VocabularyItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("VocabularyItem");
                });

            modelBuilder.Entity("LexiLoop.Models.Entities.ReviewHistory", b =>
                {
                    b.HasOne("LexiLoop.Models.Entities.VocabularyItem", "VocabularyItem")
                        .WithMany()
                        .HasForeignKey("VocabularyItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VocabularyItem");
                });

            modelBuilder.Entity("LexiLoop.Models.Entities.UserSettings", b =>
                {
                    b.HasOne("LexiLoop.Models.Entities.TelegramUser", "User")
                        .WithOne("Settings")
                        .HasForeignKey("LexiLoop.Models.Entities.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LexiLoop.Models.Entities.VocabularyItem", b =>
                {
                    b.HasOne("LexiLoop.Models.Entities.TelegramUser", "User")
                        .WithMany("VocabularyItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LexiLoop.Models.Entities.VocabularyItemCollection", b =>
                {
                    b.HasOne("LexiLoop.Models.Entities.Collection", "Collection")
                        .WithMany("VocabularyItems")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LexiLoop.Models.Entities.VocabularyItem", "VocabularyItem")
                        .WithMany("Collections")
                        .HasForeignKey("VocabularyItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("VocabularyItem");
                });

            modelBuilder.Entity("LexiLoop.Models.Entities.Collection", b =>
                {
                    b.Navigation("VocabularyItems");
                });

            modelBuilder.Entity("LexiLoop.Models.Entities.LearningSession", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("LexiLoop.Models.Entities.TelegramUser", b =>
                {
                    b.Navigation("Collections");

                    b.Navigation("Settings")
                        .IsRequired();

                    b.Navigation("VocabularyItems");
                });

            modelBuilder.Entity("LexiLoop.Models.Entities.VocabularyItem", b =>
                {
                    b.Navigation("Collections");

                    b.Navigation("Progress")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
